print('Creating tuples')
print()
A1=()
A1=(7487,1223,1566,2230)
A2=7442,'A',940
A3=(7412)
print(A1)
print(A2)
print(A3)
print()
print('Nesting tuples')
A4=A1,(6,'K')
print(A4)
print()
print('Acessing tuples')
print(A1[0])
print(A1[::-1])
print(A1[0:2])
print()
print('Addition operator')
print(A1+A2)
print()
print('Repetion operator')
print(A1*5)
print()
print('Minimum function')
print(min(A1))
print()
print('Maximum Function')
print(max(A1))
print()
print('length function')
print(len(A1))

